### ISSUE TITLE
Document usage

### ISSUE THREAD

**Issue by fernandocoronatomf** [arietimmerman/laravel-scim-server#1]
Hey mate, how's it going?
Thanks for providing this package.. could you add any documentation on how to use it?
I added the service provider but still have no route available....

**Comment by fernandocoronatomf** [comment]
OK, I figured i don't need to add the service provider on app.php but I need to add

\ArieTimmerman\Laravel\SCIMServer\RouteProvider::routes();

to my route file... the binding is not working though 

`   Route::prefix('v2')->middleware([
                'bindings',
                'ArieTimmerman\Laravel\SCIMServer\Middleware\SCIMHeaders'
            ])`

I had to add 'bindings' to your RouteProvider... I guess I can work this around but it would be great to add a list of middlewares that could be added to those routes?

Also, It would be great to be able to use another Resource as my model includes binary IDs... I can also use the Container Registry to switch the classes but I don't thin that's the best way when the package could provide a way to let us overwrite it. 

Let me know what do you think and if you need any help I can raise a PR

**Comment by arietimmerman** [comment]
Hi @fernandocoronatomf 
You're right the documentation is very limited. Thanks for providing this fix. I've implemented it.

Have you been able to get it working?

I will try to reserve some time somewhere the coming week to write a bit of documentation.

**Comment by arietimmerman** [comment]
I've made some small improvements to the documentation. Moreover, now a docker example is added.
