### ISSUE TITLE
Documentation tweak

### ISSUE THREAD

**Issue by uberbrady** [arietimmerman/laravel-scim-server#17]
I found a really nice way to override the SCIM Settings that I'd love to add to your documentation if you're interested? Method is here: https://github.com/snipe/snipe-it/pull/10802/files#diff-17714f8ce6354a7c071d6a6f7dc4840494df0850873e6192273db951138bb24f

Let me know if that would be of interest to you all - or not! That's also fine, your library, your rules :)

**Comment by arietimmerman** [comment]
I like it. Would be cool to add this to the documentation.

**Comment by uberbrady** [comment]
Excellent! I'll get something written up for you sometime next week, and will link it to this issue :)
