### ISSUE TITLE
SCIM-tracing feature?

### ISSUE THREAD

**Issue by uberbrady** [arietimmerman/laravel-scim-server#25]
Thanks again for this really spectacular piece of engineering; it's enabled us to offer SCIM support to our users and customers and has been a great success for us.

We have found that adding a SCIM-trace feature to our fork of this implementation to really pay off when troubleshooting our customers' various SCIM implementation issues. It logs the HTTP method, URL, request content, and response content into a new log file, `scim.log` - when it's turned on. The way we did it was this: https://github.com/grokability/laravel-scim-server/pull/1 and we'd be happy to offer up a similar PR back here if there's any interest. It also adds a new parameter to the `config/scim.php` as `scim.trace`, and (in our case) read from the environment as `SCIM_TRACE`, defaulting to `false`. We also ended up adding a new logging facility to target the new `scim.log` file.

Please let me know if you'd be interested in such a PR and we'd be happy to contribute it back to this project which has really helped us out. And if not - no worries! No offense will be taken. Thanks again!

**Comment by dmyers** [comment]
One idea could be in the `config.scim` file, maybe having a `log_channel` config that you set to a non-null value.

**Comment by arietimmerman** [comment]
Sounds like good ideas. A PR like this sounds good. But somehow I can't find the branch you experimented with. For now I close his one.
