### ISSUE TITLE
Possible to map extension attributes under custom schema namespace?

### ISSUE THREAD

**Issue by dmyers** [arietimmerman/laravel-scim-server#30]
I'm having some trouble getting Okta to pull in attributes with my custom schema. After looking at it for a bit, I noticed the `/scim/v2/Schemas` route has a lot of the core scim schema attributes, but doesn't include any of the ones I add under the unmapped or my custom namespace which I think might be the issue, but I'm not positive just yet.

It looks like if I understand the SCIM v2 spec, I would have to customize the `Tmilos SchemaBuilderV2` somehow in the Schema controller and somehow add my attributes with nested properties like `name`, `type`, `mutability`, etc like the core User has there.

I noticed the `scim/v2/ResourceTypes/User` endpoint has a `schemaExtensions` array which is empty too. I'm wondering if that needs to have a value to my namespace or something.

Curious if you have ran into this before. The goal I was hoping to achieve is to be able to have my application attributes such as `allow_email` to be able to be mapped between services like Okta from another system that integrates their SCIM with my service.

**Comment by arietimmerman** [comment]
Perhaps I don't understand this issue, but to me it seems like you should be able to create the mappings you'll need by leveraging the possibilities of SCIMConfig, like described in README.md. If this is not the case (and your issue is still relevant), let me know.
