### ISSUE TITLE
Examples for collections

### ISSUE THREAD

**Issue by fedeisas** [arietimmerman/laravel-scim-server#41]
The `SCIMConfig` does not maps `addresses`, `phoneNumbers`, `ims`, etc. I'm trying to implement this without success. I see the `AttributeMapping` class does have an `eloquentCollection` method. Can you share an example on how to map this? Thanks!

**Comment by pieterdt** [comment]
@fedeisas ,  I found this config a useful example: https://github.com/idaas-nl/idaas.nl/blob/893b18731464f810da9eae2e4e466b1f00fe9241/app/SCIMConfig.php#L16
