### ISSUE TITLE
Error After installation the Package when Testing the connection

### ISSUE THREAD

**Issue by Ahmedfawzy2018** [arietimmerman/laravel-scim-server#43]
Error: Class 'ArieTimmerman\Laravel\SCIM\Controllers\SCIMController' not found in file C:\xampp\htdocs\cms\app\Http\Controllers\Microsoft\SCIMController.php on line 6

- My Controller Looks like this:
<?php

namespace App\Http\Controllers\Microsoft;

use ArieTimmerman\Laravel\SCIM\Controllers\SCIMController as BaseController;
class SCIMController extends BaseController
{
    protected $model = \App\SystemUsers::class;
}

- My Routes :
Route::group(['prefix' => '/scim/v2/Users'], function () {
    Route::post('', 'Microsoft\SCIMController@store');
    Route::get('', 'Microsoft\SCIMController@index');
    Route::get('{id}', 'Microsoft\SCIMController@show');
    Route::put('{id}', 'Microsoft\SCIMController@update');
    Route::delete('{id}', 'Microsoft\SCIMController@destroy');
});

**Comment by arietimmerman** [comment]
Seems like this issue is not related to this package per se. Perhaps a composer issue.
