### ISSUE TITLE
Support for groups missing?

### ISSUE THREAD

**Issue by pieterdt** [arietimmerman/laravel-scim-server#44]
Hi, as far as I could see support for the Group endpoint is missing, or am I looking wrong?

For that reason I'm trying to implement this myself. I will be happy to share once it is finished, but I'm not there yet.

Currently I can create empty groups already (small steps :-) ). Now I'm looking into a GroupConfig that would add/remove the members. Unfortunately, I find the whole mapping structure a bit hard to understand. I'm stuck wit mapping the members to a group. Would you have some bits of advice on how to tackle this?

thanks

**Comment by arietimmerman** [comment]
The Groups endpoint is supported. It is _just_ yet another resource type.

See for example how this is done in the idaas project: https://github.com/idaas-nl/idaas.nl/blob/893b18731464f810da9eae2e4e466b1f00fe9241/app/SCIMConfig.php#L16

**Comment by pieterdt** [comment]
thx for the pointer @arietimmerman , that really helped!
