### ISSUE TITLE
Schema value not returned at the root?

### ISSUE THREAD

**Issue by atymic** [arietimmerman/laravel-scim-server#51]
Having some issues getting azure SCIM to play with this package, and i've realised it's because the attributes aren't at the root, and microsoft expects them to be.

In this package, they are nested under `urn:ietf:params:scim:schemas:core:2.0:User`, however in the scim RFC and microsoft examples, all the properties under this namespace are in the root.

Any ideas? 
cc @uberbrady if you ran across this in your work 

https://datatracker.ietf.org/doc/html/rfc7644#section-3.4

**Comment by atymic** [comment]
🤦 should have set `omit_main_schema_in_return`

**Comment by arietimmerman** [comment]
Good to hear you've found a fix.
As Azure AD/Entra ID is probably one of the most important SCIM clients for this package, I probably should consider documenting how to integrate it with this.
